# -*- coding: utf-8 -*-
'''
    Author    : Huseyin BIYIK <husenbiyik at hotmail>
    Year      : 2016
    License   : GPL

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

one = {
    'aa': 'afar',
    'ab': 'abkhazian',
    'ae': 'avestan',
    'af': 'afrikaans',
    'ak': 'akan',
    'am': 'amharic',
    'an': 'aragonese',
    'ar': 'arabic',
    'as': 'assamese',
    'av': 'avaric',
    'ay': 'aymara',
    'az': 'azerbaijani',
    'ba': 'bashkir',
    'be': 'belarusian',
    'bg': 'bulgarian',
    'bh': 'bihari',
    'bi': 'bislama',
    'bm': 'bambara',
    'bn': 'bengali',
    'bo': 'tibetan',
    'br': 'breton',
    'bs': 'bosnian',
    'ca': 'catalan',
    'ce': 'chechen',
    'ch': 'chamorro',
    'co': 'corsican',
    'cr': 'cree',
    'cs': 'czech',
    'cu': 'church',
    'cv': 'chuvash',
    'cy': 'welsh',
    'da': 'danish',
    'de': 'german',
    'dv': 'divehi',
    'dz': 'dzongkha',
    'ee': 'ewe',
    'el': 'greek',
    'en': 'english',
    'eo': 'esperanto',
    'es': 'spanish',
    'et': 'estonian',
    'eu': 'basque',
    'fa': 'persian',
    'ff': 'fulah',
    'fi': 'finnish',
    'fj': 'fijian',
    'fo': 'faroese',
    'fr': 'french',
    'fy': 'western',
    'ga': 'irish',
    'gd': 'gaelic',
    'gl': 'galician',
    'gn': 'guarani',
    'gu': 'gujarati',
    'gv': 'manx',
    'ha': 'hausa',
    'he': 'hebrew',
    'hi': 'hindi',
    'ho': 'hiri',
    'hr': 'croatian',
    'ht': 'haitian',
    'hu': 'hungarian',
    'hy': 'armenian',
    'hz': 'herero',
    'ia': 'interlingua',
    'id': 'indonesian',
    'ie': 'interlingue',
    'ig': 'igbo',
    'ii': 'sichuan',
    'ik': 'inupiaq',
    'io': 'ido',
    'is': 'icelandic',
    'it': 'italian',
    'iu': 'inuktitut',
    'ja': 'japanese',
    'jv': 'javanese',
    'ka': 'georgian',
    'kg': 'kongo',
    'ki': 'kikuyu',
    'kj': 'kuanyama',
    'kk': 'kazakh',
    'kl': 'kalaallisut',
    'km': 'central',
    'kn': 'kannada',
    'ko': 'korean',
    'kr': 'kanuri',
    'ks': 'kashmiri',
    'ku': 'kurdish',
    'kv': 'komi',
    'kw': 'cornish',
    'ky': 'kirghiz',
    'la': 'latin',
    'lb': 'luxembourgish',
    'lg': 'ganda',
    'li': 'limburgan',
    'ln': 'lingala',
    'lo': 'lao',
    'lt': 'lithuanian',
    'lu': 'luba katanga',
    'lv': 'latvian',
    'mg': 'malagasy',
    'mh': 'marshallese',
    'mi': 'maori',
    'mk': 'macedonian',
    'ml': 'malayalam',
    'mn': 'mongolian',
    'mr': 'marathi',
    'ms': 'malay',
    'mt': 'maltese',
    'my': 'burmese',
    'na': 'nauru',
    'nb': 'bokmål',
    'nd': 'ndebele',
    'ne': 'nepali',
    'ng': 'ndonga',
    'nl': 'dutch',
    'nn': 'norwegian',
    'no': 'norwegian',
    'nr': 'ndebele',
    'nv': 'navajo',
    'ny': 'chichewa',
    'oc': 'occitan',
    'oj': 'ojibwa',
    'om': 'oromo',
    'or': 'oriya',
    'os': 'ossetian',
    'pa': 'panjabi',
    'pi': 'pali',
    'pl': 'polish',
    'ps': 'pushto',
    'pt': 'portuguese',
    'qu': 'quechua',
    'rm': 'romansh',
    'rn': 'rundi',
    'ro': 'romanian',
    'ru': 'russian',
    'rw': 'kinyarwanda',
    'sa': 'sanskrit',
    'sc': 'sardinian',
    'sd': 'sindhi',
    'se': 'northern',
    'sg': 'sango',
    'si': 'sinhala',
    'sk': 'slovak',
    'sl': 'slovenian',
    'sm': 'samoan',
    'sn': 'shona',
    'so': 'somali',
    'sq': 'albanian',
    'sr': 'serbian',
    'ss': 'swati',
    'st': 'sotho',
    'su': 'sundanese',
    'sv': 'swedish',
    'sw': 'swahili',
    'ta': 'tamil',
    'te': 'telugu',
    'tg': 'tajik',
    'th': 'thai',
    'ti': 'tigrinya',
    'tk': 'turkmen',
    'tl': 'tagalog',
    'tn': 'tswana',
    'to': 'tonga',
    'tr': 'turkish',
    'ts': 'tsonga',
    'tt': 'tatar',
    'tw': 'twi',
    'ty': 'tahitian',
    'ug': 'uighur',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'uz': 'uzbek',
    've': 'venda',
    'vi': 'vietnamese',
    'vo': 'volapük',
    'wa': 'walloon',
    'wo': 'wolof',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'za': 'zhuang',
    'zh': 'chinese',
    'zu': 'zulu',
    # below are the ones in -3 but not in -1
    'ace': 'achinese',
    'ach': 'acoli',
    'ada': 'adangme',
    'ady': 'adyghe',
    'ain': 'ainu',
    'ale': 'aleut',
    'alt': 'southern altai',
    'anp': 'angika',
    'arn': 'mapudungun',
    'arp': 'arapaho',
    'arw': 'arawak',
    'ast': 'asturian',
    'awa': 'awadhi',
    'bal': 'baluchi',
    'ban': 'balinese',
    'bas': 'basa',
    'bej': 'beja',
    'bem': 'bemba',
    'bho': 'bhojpuri',
    'bik': 'bikol',
    'bin': 'bini',
    'bla': 'siksika',
    'bra': 'braj',
    'bua': 'buriat',
    'bug': 'buginese',
    'byn': 'bilin',
    'cad': 'caddo',
    'car': 'galibi carib',
    'ceb': 'cebuano',
    'chk': 'chuukese',
    'chm': 'mari',
    'chn': 'chinook jargon',
    'cho': 'choctaw',
    'chp': 'chipewyan',
    'chr': 'cherokee',
    'chy': 'cheyenne',
    'crh': 'crimean tatar',
    'csb': 'kashubian',
    'dak': 'dakota',
    'dar': 'dargwa',
    'del': 'delaware',
    'den': 'slave',
    'dgr': 'dogrib',
    'din': 'dinka',
    'doi': 'dogri',
    'dsb': 'lower sorbian',
    'dua': 'duala',
    'dyu': 'dyula',
    'efi': 'efik',
    'eka': 'ekajuk',
    'ewo': 'ewondo',
    'fan': 'fang',
    'fat': 'fanti',
    'fil': 'filipino',
    'fon': 'fon',
    'frr': 'northern frisian',
    'frs': 'eastern frisian',
    'fur': 'friulian',
    'gaa': 'ga',
    'gay': 'gayo',
    'gba': 'gbaya',
    'gil': 'gilbertese',
    'gon': 'gondi',
    'gor': 'gorontalo',
    'grb': 'grebo',
    'gsw': 'swiss german',
    'gwi': 'gwichʼin',
    'hai': 'haida',
    'haw': 'hawaiian',
    'hil': 'hiligaynon',
    'hmn': 'hmong',
    'hsb': 'upper sorbian',
    'hup': 'hupa',
    'iba': 'iban',
    'ilo': 'iloko',
    'inh': 'ingush',
    'jpr': 'judeo persian',
    'jrb': 'judeo arabic',
    'kaa': 'kara kalpak',
    'kab': 'kabyle',
    'kac': 'kachin',
    'kam': 'kamba',
    'kbd': 'kabardian',
    'kha': 'khasi',
    'kmb': 'kimbundu',
    'kok': 'konkani',
    'kos': 'kosraean',
    'kpe': 'kpelle',
    'krc': 'karachay balkar',
    'krl': 'karelian',
    'kru': 'kurukh',
    'kum': 'kumyk',
    'kut': 'kutenai',
    'lad': 'ladino',
    'lah': 'lahnda',
    'lam': 'lamba',
    'lez': 'lezghian',
    'lol': 'mongo',
    'loz': 'lozi',
    'lua': 'luba lulua',
    'lui': 'luiseno',
    'lun': 'lunda',
    'luo': 'luo',
    'lus': 'lushai',
    'mad': 'madurese',
    'mag': 'magahi',
    'mai': 'maithili',
    'mak': 'makasar',
    'man': 'mandingo',
    'mas': 'masai',
    'mdf': 'moksha',
    'mdr': 'mandar',
    'men': 'mende',
    'mic': 'mi kmaq',
    'min': 'minangkabau',
    'mnc': 'manchu',
    'mni': 'meitei',
    'moh': 'mohawk',
    'mos': 'mossi',
    'mus': 'creek',
    'mwl': 'mirandese',
    'mwr': 'marwari',
    'myv': 'erzya',
    'nap': 'neapolitan',
    'nds': 'low german',
    'new': 'nepal bhasa',
    'nia': 'nias',
    'niu': 'niuean',
    'nog': 'nogai',
    'nqo': 'nko',
    'nso': 'pedi',
    'nym': 'nyamwezi',
    'nyn': 'nyankole',
    'nyo': 'nyoro',
    'nzi': 'nzima',
    'osa': 'osage',
    'pag': 'pangasinan',
    'pam': 'pampanga',
    'pap': 'papiamento',
    'pau': 'palauan',
    'pon': 'pohnpeian',
    'raj': 'rajasthani',
    'rap': 'rapanui',
    'rar': 'rarotongan',
    'rom': 'romany',
    'rup': 'macedo romanian',
    'sad': 'sandawe',
    'sah': 'yakut',
    'sas': 'sasak',
    'sat': 'santali',
    'scn': 'sicilian',
    'sco': 'scots',
    'sel': 'selkup',
    'shn': 'shan',
    'sid': 'sidamo',
    'sma': 'southern sami',
    'smj': 'lule sami',
    'smn': 'inari sami',
    'sms': 'skolt sami',
    'snk': 'soninke',
    'srn': 'sranan tongo',
    'srr': 'serer',
    'suk': 'sukuma',
    'sus': 'susu',
    'syr': 'syriac',
    'tem': 'timne',
    'ter': 'tereno',
    'tet': 'tetum',
    'tig': 'tigre',
    'tiv': 'tiv',
    'tkl': 'tokelau',
    'tli': 'tlingit',
    'tmh': 'tamashek',
    'tog': 'tonga',
    'tpi': 'tok pisin',
    'tsi': 'tsimshian',
    'tum': 'tumbuka',
    'tvl': 'tuvaluan',
    'tyv': 'tuvinian',
    'udm': 'udmurt',
    'umb': 'umbundu',
    'vai': 'vai',
    'vot': 'votic',
    'wal': 'wolaytta',
    'war': 'waray',
    'was': 'washo',
    'xal': 'kalmyk',
    'yao': 'yao',
    'yap': 'yapese',
    'zap': 'zapotec',
    'zen': 'zenaga',
    'zgh': 'standard moroccan tamazight',
    'zun': 'zuni',

    }
